<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BaiVietSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('bai_viets')->delete();

        DB::table('bai_viets')->truncate();

        DB::table('bai_viets')->insert([
            ['id_chuyen_muc' => 2, 'ten_bai_viet' => '50 địa điểm du lịch Đà Nẵng HẤP DẪN NHẤT bạn tha hồ lựa chọn', 'mo_ta_ngan' => 'Du lịch Đà Nẵng thì nên đi đâu, chơi gì? Top 50 địa điểm du lịch Đà Nẵng sẽ giới thiệu đến bạn những địa điểm du lịch HOT nhất, HẤP DẪN nhất mà bạn không thể bỏ qua khi đến với thành phố của những cây cầu.', 'mo_ta_chi_tiet' => 'Đưa vào hoạt động năm 2013, điểm tham quan Đà Nẵng cầu Rồng là một trong những địa điểm du lịch mới ở Đà Nẵng hấp dẫn du khách. Với thiết kế độc đáo mang hình dáng con rồng bắc qua sông Hàn thơ mộng, cầu Rồng là cây cầu thứ 7 tạo nên biểu tượng “thành phố của những cây cầu”. Đến đây vào các ngày cuối tuần, bạn còn xem được cảnh rồng phun lửa, phun nước sống động. Nằm ở phía nam bán đảo Sơn Trà, Bãi Bụt là một trong những địa điểm du lịch Đà Nẵng miễn phí đáng đến nhất. Được mệnh danh là tuyệt cảnh dưới chân Chùa Linh Ứng, Bãi Bụt là nơi nhiều du khách trong và ngoài nước chọn làm nơi tham quan, tắm biển, ngắm san hô, khám phá các loài sinh vật biển,... khi đến du lịch tại Đà Nẵng.', 'hinh_anh' => 'https://statics.vinpearl.com/du-lich-da-nang_1657939501.JPG', 'tinh_trang' => '1'],
            ['id_chuyen_muc' => 2, 'ten_bai_viet' => 'Các điểm ngắm lễ hội pháo hoa Đà Nẵng', 'mo_ta_ngan' => 'Pháo hoa Đà Nẵng có thể quan sát ở các khu vực xung quanh đường Bạch Đằng, Trần Hưng Đạo, trên những cây cầu bắc qua sông Hàn. ', 'mo_ta_chi_tiet' => 'Pháo hoa Đà Nẵng có thể quan sát ở các khu vực xung quanh đường Bạch Đằng, Trần Hưng Đạo, trên những cây cầu bắc qua sông Hàn.

Lễ hội pháo hoa quốc tế Đà Nẵng lần thứ 12 năm 2024 (DIFF 2024) khai mạc ngày 8/6 và kéo dài đến 13/7.

DIFF 2024 có chủ đề "Made in Unity - Kết nối toàn cầu - Rạng rỡ năm châu", với thông điệp về một thế giới hòa bình, hữu nghị, nhân văn và tôn vinh những giá trị truyền cảm hứng cho cộng đồng. Các đêm biểu diễn gồm Việt Nam - ĐKVĐ Pháp (8/6 - khai mạc), Italy - Mỹ (15/6), Đức - Ba Lan (22/6), Trung Quốc - Phần Lan (29/6) và đêm chung kết ngày 13/7. Mỗi đêm có một chủ đề riêng.

Nếu có mặt ở Đà Nẵng dịp này, du khách có thể chiêm ngưỡng các màn pháo hoa từ những địa điểm sau đây, theo gợi ý của anh Hùng Nguyễn, đại diện một công ty du lịch tại Đà Nẵng, website của Trung tâm Xúc tiến Du lịch Đà Nẵng và BTC DIFF 2024.

Sân khấu chính

Sân khấu chính của sự kiện nằm tại vỉa hè đường Trần Hưng Đạo, đối diện khu vực bắn pháo hoa cuối đường Bạch Đằng giao với đường 3/2. Đây là vị trí quan sát tốt nhất tất cả các màn tranh tài với khung cảnh đẹp, không phải chen lấn và không bị vướng tầm nhìn.

Sân khấu có sức chứa hơn 10.000 chỗ ngồi. Giá vé dao động từ 800.000 đồng đến 3 triệu đồng, với 5 hạng ghế khác nhau.', 'hinh_anh' => 'https://i1-dulich.vnecdn.net/2024/06/07/cau-1717753399-5280-1717754470.jpg?w=1020&h=0&q=100&dpr=1&fit=crop&s=DrYUHujUeWU8BEPrHeeLTQ', 'tinh_trang' => '1'],
            ['id_chuyen_muc' => 1, 'ten_bai_viet' => 'Top 30+ đặc sản Đà Nẵng nên thưởng thức và mua về làm quà', 'mo_ta_ngan' => '30+ món ngon, đặc sản Đà Nẵng mà bạn nhất định phải thử và mua về làm quà cho người thân, gia đình, bạn bè trong chuyến du lịch sắp tới, đừng bỏ qua nha!', 'mo_ta_chi_tiet' => 'Món ăn đặc sản Đà Nẵng không thiếu, thậm chí có ngồi kể cả ngày cũng không hết được cả trăm thức quà ngon lành mang đậm văn hóa ẩm thực miền Trung. Nhưng để gọi là đặc sắc nhất, nổi bật nhất, du khách ghé thăm không thể không thử phải kể đến mấy chục món trứ danh dưới đây. Quả không ngoa khi nói Đà Nẵng là xứ ẩm thực đặc biệt, đa dạng với đủ các loại món ngon mà món nào ăn một lần người ta cũng sẽ nhớ mãi.', 'hinh_anh' => 'https://statics.vinpearl.com/dac-san-da-nang-1.jpg', 'tinh_trang' => '1'],
            ['id_chuyen_muc' => 1, 'ten_bai_viet' => 'Ba món Việt vào top 100 món đường phố ngon nhất thế giới', 'mo_ta_ngan' => 'Bánh mì, phở và cơm tấm của Việt Nam được gọi tên trong top 100 món ăn đường phố ngon nhất thế giới của Taste Atlas. ', 'mo_ta_chi_tiet' => 'Bánh mì, phở và cơm tấm của Việt Nam được gọi tên trong top 100 món ăn đường phố ngon nhất thế giới của Taste Atlas.

Danh sách mới 100 món ăn đường phố ngon nhất thế giới do chuyên trang ẩm thực Taste Atlas cập nhật giữa tháng 5, có 3 món ăn của Việt Nam được nhắc đến gồm bánh mì, phở và cơm tấm.

Tiêu chí bình chọn các món ăn dựa trên ý kiến của các chuyên gia, thực khách khắp thế giới và mức độ nổi tiếng, hương vị độc đáo cũng như được nhiều người yêu thích của mỗi món.

Bánh mì của Việt Nam xếp thứ 6 trên 100, với tổng 4,6 sao trên 5. Các chuyên gia của Taste Atlas cũng hướng dẫn thực khách quốc tế phát âm món ăn này là "bun mee" và giới thiệu đây là món ăn phổ biến của người dân địa phương. Thành phần chính gồm bánh mì giòn baguette, một di sản của ẩm thực Pháp du nhập vào Việt Nam, các loại nhân ăn kèm gồm thịt, ngò, ớt, dưa chua, rau thơm thể hiện khẩu vị của người Việt.', 'hinh_anh' => 'https://i1-dulich.vnecdn.net/2024/05/29/bd4aea842dba436583ba436a4f77e4-5308-6314-1716949326.jpg?w=1020&h=0&q=100&dpr=1&fit=crop&s=Glw8uYohuPvfdnGM1cxFsg', 'tinh_trang' => '1'],
            ['id_chuyen_muc' => 1, 'ten_bai_viet' => 'Thưởng thức dạ yến hoàng cung Huế', 'mo_ta_ngan' => 'Với 2 triệu đồng mỗi người, thực khách được thưởng thức 7 món ẩm thực, nghe ca Huế và tìm hiểu về yến tiệc của giới quý tộc trong hoàng cung.', 'mo_ta_chi_tiet' => 'Dạ yến hoàng cung là hoạt động trong chuỗi sự kiện thuộc tuần lễ Festival nghệ thuật quốc tế Huế 2024. Đêm hội ẩm thực diễn ra tối 8/6 tại sân điện Cần Chánh bên trong Đại nội Huế. Dạ yến hoàng cung tái hiện Ngự yến của vua triều Nguyễn thiết đãi các hoàng thân trong cung cấm ngày xưa. Trước khi dạ yến bắt đầu, một diễn viên thủ vai vị quan đứng giữa sân khấu, lắc chiếc chuông nhỏ để ra hiệu dừng đội nhạc và sự chú ý của quan khách. Sau đó quan bẩm báo những món ăn sẽ được đưa lên bàn tiệc. Tiếp đó, đội ngũ phục vụ trong tà áo dài kiểu cung nữ cung đình sẽ đưa các món ăn đến từng bàn. Theo ban tổ chức, chương trình Dạ yến hoàng cung ngoài việc quảng bá du lịch còn giúp thực khách có cơ hội trải nghiệm ẩm thực cung đình một cách chân thực. Các món ăn trong buổi dạ yến được thực hiện bởi các đầu bếp của một khách sạn ở Huế. Thực đơn năm nay có 7 món, thay đổi so với các kì Festival trước.', 'hinh_anh' => 'https://i1-dulich.vnecdn.net/2024/06/09/BIT-8011-1717896647.jpg?w=1200&h=0&q=100&dpr=1&fit=crop&s=q5wOEf-J9r3buwzVzEJPTw', 'tinh_trang' => '1'],
            ['id_chuyen_muc' => 2, 'ten_bai_viet' => 'Ngũ Hành Sơn Đà Nẵng - “Nam Thiên Danh Thắng” trứ danh', 'mo_ta_ngan' => 'Ngũ Hành Sơn là quần thể gồm 6 ngọn núi mọc gần nhau, quy tụ đủ những vẻ đẹp từ thiên nhiên và tâm linh, mang đến cho du khách hành trình tham quan, khám phá thắng cảnh tuyệt vời.', 'mo_ta_chi_tiet' => 'Ngũ Hành Sơn là tuyệt tác về cảnh quan thiên nhiên mà tạo hóa ban tặng cho vùng đất Đà Nẵng. Có vẻ đẹp hài hòa của vùng sinh thái tự nhiên đan xen cùng với đời sống văn hóa tâm linh nên nơi đây càng ngày càng thu hút khách du lịch đến tham quan hàng năm. Địa điểm du lịch Đà Nẵng Ngũ Hành Sơn nằm ở khu vực có vị trí địa lý hết sức thuận lợi, cách trung tâm thành phố Đà Nẵng 8km. Đây là điểm đến được du khách yêu mến trên hành trình tham quan các vùng đất thuộc con đường di sản Miền Trung như: Cố Đô Huế – Ngũ Hành Sơn – Phố cổ Hội An - Khu di tích đền tháp Mỹ Sơn.', 'hinh_anh' => 'https://statics.vinpearl.com/ngu-hanh-son-01_1629767291.jpg', 'tinh_trang' => '1'],
            ['id_chuyen_muc' => 3, 'ten_bai_viet' => 'Combo 3N2Đ tàu Phú Quốc Express & VinHolidays Fiesta hoặc TK Phú Quốc Hotel', 'mo_ta_ngan' => 'Khởi động một mùa hè diệu kỳ, Vinpearl kết hợp với hãng tàu 5 sao Phú Quốc Express giới thiệu combo khám phá đảo ngọc thiên đường với hành trình ấn tượng bằng tàu cao tốc Phú Quốc Express ', 'mo_ta_chi_tiet' => 'Hãng tàu với công nghệ hiện đại, tiên tiến nhất của thế giới hiện nay: Tàu cao tốc hai thân vận chuyển hành khách đường biển, với chất lượng kỹ thuật và độ an toàn Châu Âu, sử dụng thiết bị động lực của Rolls Royce, dịch vụ cao cấp chuẩn 5 sao. Tốc độ tối ưu lên tới 30 hải lý/giờ, mang bạn đến đảo với thời gian tiết kiệm nhất.  Tàu gồm 2 khoang: khoang phổ thông và khoang VIP. Khoang VIP có thiết kế ghế bọc da thật, có khả năng ngả 130 độ và màn hình giải trí, hệ thống âm thanh và tai nghe không dây rất tiện nghi và sang trọng phục vụ khách, trong khi đó khoang phổ thông cũng được thiết kế rất sang trọng với vách khoang ốp da, sàn tàu thiết kế chống ồn và say sóng. Trên tàu còn có hệ thống camera hành trình, ghi lại thông tin hành trình của tàu. Boong tàu được thiết kế với sức chứa lên tới 50 người. Với những ai thích không gian mở, không thích ngồi trong khoang tàu, có thể lên boong tàu để ngắm cảnh và chụp hình.', 'hinh_anh' => 'https://booking-static.vinpearl.com/tours/2c563f58e6244070b23cf40ef5f9cc9a_DJI_0527%20(1).jpg', 'tinh_trang' => '1'],
            ['id_chuyen_muc' => 3, 'ten_bai_viet' => 'Trọn bộ kinh nghiệm, điểm đến & combo du lịch Phú Quốc từ A - Z 2024', 'mo_ta_ngan' => 'Du lịch Phú Quốc với trọn bộ cẩm nang về thời điểm, khí hậu, phương tiện đi lại, kế hoạch ăn - chơi - ngủ - nghỉ từ A - Z sau đây sẽ giúp mọi du khách tận hưởng kỳ nghỉ của mình trọn vẹn nhất!', 'mo_ta_chi_tiet' => 'Thuộc địa phận tỉnh Kiên Giang, nằm trong vịnh Thái Lan, đảo Phú Quốc từ lâu đã nổi tiếng với du khách từ mọi miền đất nước và cả khách du lịch quốc tế. Không chỉ là hòn đảo xinh đẹp với phong cảnh thiên nhiên yên bình, hoang sơ, khí hậu thuận lợi cho hoạt động vui chơi, nghỉ dưỡng, Phú Quốc còn là điểm đến lý tưởng cho nhiều hoạt động khám phá thiên nhiên kỳ thú.', 'hinh_anh' => 'https://statics.vinpearl.com/du-lich-phu-quoc-hoang-hon_1649836308.jpg', 'tinh_trang' => '1'],
            ['id_chuyen_muc' => 3, 'ten_bai_viet' => 'Lịch trình du lịch Phú Quốc 3 ngày cho nhóm bạn vui hết cỡ', 'mo_ta_ngan' => 'Lịch trình du lịch Phú Quốc 3 ngày đầy đủ và chi tiết dưới đây sẽ giúp các hội bạn thân khám phá trọn vẹn những bãi biển thơ mộng, những khu vui chơi, giải trí hấp dẫn nhất Phú Quốc.', 'mo_ta_chi_tiet' => 'Phú Quốc đẹp nhất từ tháng 10 đến tháng 4 hàng năm, khi thời tiết ít mưa, thuận lợi cho các hoạt động du lịch. Sau đây là những gợi ý lịch trình du lịch Phú Quốc 3 ngày từ độc giả Marine Poy cùng nhóm bạn 7 người trong 3 ngày. Mỗi lần đến với Phú Quốc, du khách nên dành ít nhất 3-4 ngày để trải nghiệm được hết các địa điểm du lịch hấp dẫn. Một lịch trình 3 ngày tại Phú Quốc có thể đảm bảo tiết kiệm thời gian và chi phí đi lại sẽ có mức giá khoảng 5 triệu đồng/người.', 'hinh_anh' => 'https://statics.vinpearl.com/Hinh-anh-lich-trinh-du-lich-phu-quoc-cho-nhom-ban-3-ngay-1.jpg', 'tinh_trang' => '1'],
        ]);
    }
}
